package com.example.restuarantrater;

import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.ToggleButton;

public class MainActivity extends AppCompatActivity {

    private restaurant currentRestaurant = new restaurant();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        initTextChangedEvents();
        initSaveButton();
        initChangeScreen();
    }

    private void initSaveButton () {

        Button saveButton = findViewById(R.id.saveBtn);
        TextView results = findViewById(R.id.resultsLabel);
        saveButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                boolean wasSuccessful;
                hideKeyboard();
                restaurantDataSource ds = new restaurantDataSource(MainActivity.this);
                try {
                    ds.open();
                    if(currentRestaurant.getRestaurantID() == -1) {
                        wasSuccessful = ds.insertRestaurant(currentRestaurant);
                        if (wasSuccessful) {
                            int newId = ds.getLastID();
                            currentRestaurant.setRestaurantID(newId);
                            String added = "Restaurant Added";
                            results.setText(added);

                        }
                    } else {
                        wasSuccessful = ds.updateRestaurant(currentRestaurant);
                        String updated = "Restaurant Updated";
                        results.setText(updated);
                    }
                    ds.close();
                } catch (Exception e) {
                    wasSuccessful = false;
                }
            }
        });
    }


    private void initTextChangedEvents() {

        final EditText etName = findViewById(R.id.nameInput);
        etName.addTextChangedListener(new TextWatcher() {
            @Override
            public void afterTextChanged(Editable s) {
                currentRestaurant.setName(etName.getText().toString());
            }

            @Override
            public void beforeTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
        });

        final EditText etStreetAddress = findViewById(R.id.streetInput);
        etStreetAddress.addTextChangedListener(new TextWatcher() {
            @Override
            public void afterTextChanged(Editable s) {
                currentRestaurant.setStreet(etStreetAddress.getText().toString());
            }

            @Override
            public void beforeTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
        });

        final EditText etCity = findViewById(R.id.cityInput);
        etCity.addTextChangedListener(new TextWatcher() {
            @Override
            public void afterTextChanged(Editable s) {
                currentRestaurant.setCity(etCity.getText().toString());
            }

            @Override
            public void beforeTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
        });

        final EditText etState = findViewById(R.id.stateInput);
        etState.addTextChangedListener(new TextWatcher() {
            @Override
            public void afterTextChanged(Editable s) {
                currentRestaurant.setState(etState.getText().toString());
            }

            @Override
            public void beforeTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
        });

        final EditText etZipCode = findViewById(R.id.zipInput);
        etZipCode.addTextChangedListener(new TextWatcher() {
            @Override
            public void afterTextChanged(Editable s) {
                currentRestaurant.setZipCode(etZipCode.getText().toString());
            }

            @Override
            public void beforeTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
        });
    }


    private void initChangeScreen() {
        Button addMealBtn = findViewById(R.id.addMealBtn);
        addMealBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(MainActivity.this, RateDish.class);
                intent.putExtra("currentRestaurant",currentRestaurant.getRestaurantID());
                intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP); //clears the stack trace
                startActivity(intent);

            }
        });
    }


    private void hideKeyboard () {
        InputMethodManager imm = (InputMethodManager) getSystemService(MainActivity.this.INPUT_METHOD_SERVICE);

        EditText nameInput = findViewById(R.id.nameInput);
        imm.hideSoftInputFromWindow(nameInput.getWindowToken(), 0);

        EditText addressInput = findViewById(R.id.streetInput);
        imm.hideSoftInputFromWindow(addressInput.getWindowToken(), 0);

        EditText stateInput = findViewById(R.id.stateInput);
        imm.hideSoftInputFromWindow(stateInput.getWindowToken(), 0);

        EditText cityInput = findViewById(R.id.cityInput);
        imm.hideSoftInputFromWindow(cityInput.getWindowToken(), 0);

        EditText zipCodeInput = findViewById(R.id.zipInput);
        imm.hideSoftInputFromWindow(zipCodeInput.getWindowToken(), 0);
    }

}