package com.example.restuarantrater;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RatingBar;
import android.widget.TextView;

import java.nio.file.WatchEvent;

public class RateDish extends AppCompatActivity {

    private dish currentDish = new dish();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_rate_dish);

        initTextChangedEvents();
        initSubmitButton();
    }


    private void initTextChangedEvents() {

        final EditText etName = findViewById(R.id.dishNameInput);
        etName.addTextChangedListener(new TextWatcher() {
            @Override
            public void afterTextChanged(Editable s) {
                currentDish.setName(etName.getText().toString());
            }
            @Override
            public void beforeTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
        });

        final EditText etType = findViewById(R.id.dishTypeInput);
        etType.addTextChangedListener(new TextWatcher() {
            @Override
            public void afterTextChanged(Editable s) {
                currentDish.setType(etType.getText().toString());
            }

            @Override
            public void beforeTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // autogenerated method for Text Watcher
            }
        });

        final RatingBar etRating = findViewById(R.id.ratingBar);
        etRating.setOnRatingBarChangeListener(new RatingBar.OnRatingBarChangeListener() {
            @Override
            public void onRatingChanged(RatingBar ratingBar, float rating, boolean fromUser) {
                currentDish.setRating(String.valueOf(ratingBar.getRating()));
            }
        });

        currentDish.setRestaurantID(0);
    }

    private void initSubmitButton () {

        Button submitButton = findViewById(R.id.submitBtn);
        TextView results = findViewById(R.id.resultsLabel);
        EditText type = findViewById(R.id.dishTypeInput);
        EditText name = findViewById(R.id.dishNameInput);
        submitButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                boolean wasSuccessful;
                dishDataSource dds = new dishDataSource(RateDish.this);
                try {
                    dds.open();
                    if(currentDish.getDishID() == -1) {
                        wasSuccessful = dds.insertDish(currentDish);
                        results.setText("Your meal has been added");
                        name.setText("");
                        type.setText("");

                        //currentDish.setRestaurantID(newId);
                    }
                    dds.close();
                } catch (Exception e) {
                    wasSuccessful = false;
                }
            }
        });
    }

}